import '/public/styles.css'
// import { Inter } from 'next/font/google'
// const inter = Inter({ subsets: ['latin'] })

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' data-theme='dark'>
			{/* <body className={inter.className}>{children}</body> */}
			<body className='bg-gray-100'>{children}</body>
		</html>
	)
}
