import '/public/styles.css'

export const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
	return (
		<html lang='en' data-theme='light'>
			<body className='bg-gray-100 w-full desktop:max-w-5xl mx-auto'>
				{children}
			</body>
		</html>
	)
}
//
